<center><img src="https://raw.githubusercontent.com/Masterx-AI/Project_Housing_Price_Prediction_/main/hs.jpg" style="width: 700px;"/>

# Importing libraries üêç

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Dataset üìÅ

In [2]:
df = pd.read_csv("house_prices.csv")

In [3]:
# Random 10 samples of data
df.sample(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
114,6020000,6800,2,1,1,yes,yes,yes,no,no,2,no,furnished
166,5320000,7800,3,1,1,yes,no,yes,no,yes,2,yes,unfurnished
53,7350000,5150,3,2,4,yes,no,no,no,yes,2,no,semi-furnished
58,7210000,7680,4,2,4,yes,yes,no,no,yes,1,no,semi-furnished
217,4830000,6862,3,1,2,yes,no,no,no,yes,2,yes,furnished
171,5250000,10269,3,1,1,yes,no,no,no,no,1,yes,semi-furnished
432,3290000,6060,3,1,1,yes,yes,yes,no,no,0,no,furnished
499,2660000,3630,3,3,2,no,yes,no,no,no,0,no,unfurnished
259,4473000,6360,2,1,1,yes,no,yes,no,yes,1,no,furnished
474,2975000,4352,4,1,2,no,no,no,no,no,1,no,unfurnished

In [4]:
# Data Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [5]:
df.shape # data shape

(545, 13)

In [6]:
df.describe() # data stats

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [7]:
df.isnull().sum() # null values check

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [8]:
df.duplicated().sum() # duplicate values check

0

In [9]:
data=df.copy()

#### 1. Create a scatter plot

- the x axis should be the area
- the y axis should be the price
- the color of each data point should be based on the furnishing status

In [10]:
# Put your answer here

#### 2. Apply the `get_dummies()` method to the categorical columns below.

- furnishingstatus
- mainroad
- guestroom
- basement
- hotwaterheating
- airconditioning
- prefarea

In [11]:
# Put your answer here

#### 3. Drop the categorical columns below.

- furnishingstatus
- mainroad
- guestroom
- basement
- hotwaterheating
- airconditioning
- prefarea

In [12]:
# Put your answer here

#### 4. Split the data set into a training and test set

In [13]:
# Put your answer here

#### 4. Use the the `MinMaxScaler()` method to scale down the training and test set.

In [14]:
# Put your answer here

#### 5. Create a new instance of a Linear Regression model

In [15]:
# Put your answer here

#### 6. Use the `fit()` method to train your model using the training set.

In [16]:
# Put your answer here

#### 7. Use the `predict()` method using the test set

In [17]:
 # Put your answer here

#### 7. Get the R2 Score

In [18]:
# Put your answer here

8. #### Use the normal equation to get the optimal slope and intercept

In [19]:
# Put your answer here